### ISSUE TITLE
[FEAT] 배포 세팅

### ISSUE THREAD

**Issue by ddolboghi** [SKY-HORSE-MAN-POWER/BE_Auction#1]
**기능 설명**

- [x] mysql 의존성 추가
- [x] eureka client 의존성 추가
- [x] eureka client 설정
- [x] dockerfile 작성

- [x] 테스트 API 작성
 
**추가 설명**
MSA를 위한 eureka client 설정과 정상 작동 여부를 알기위해 테스트 API를 만듭니다.
docker를 이용한 배포를 위해 dockerfile을 작성합니다.

**Comment by chanchanwoong** [comment]
감사합니다~
